# Generated by Django 6.0.1 on 2026-02-19 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(db_index=True, max_length=5, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
